# Generated by Django 5.0 on 2024-05-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='member',
        ),
    ]
